firebase/firebase-admin-dotnet

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs
=> Implemented AndroidNotification API

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Extensions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Message.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushNotification.cs
* Implemented `WebpushConfig` and `WebpushNotification` types
* Removed an unused extension method (`IEnumerable.Copy()`)
* Made some internal properties private for better encapsulation
=> Implemented FCM Webpush  API

FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
A couple of minor rewordings based on the feedback received from the docs team.
=> Minor API doc update

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Extensions.cs
* Making the user management initialization thread-safe
* Cleaning up the lazy loading code, and the `FirebaseAuth.Delete()`.
* Exposing a new `FirebaseAuth.SetCustomUserClaimsAsync()` method that accepts a cancellation token as a second argument.
* Introducing a couple of helper functions to `Extensions` to make it easier to send JSON requests, and tear down managed resources.
=> Refactoring the user management code

FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/HttpPublicKeySource.cs
These lint errors popped up when compiling for .NET 4.5:
```
Auth/HttpPublicKeySource.cs(124,30): error SA1009: Closing parenthesis should not be followed by a space. [/usr/local/google/home/hkj/Projects/firebase-admin-dotnet/public/FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj]
Auth/FirebaseTokenVerifier.cs(222,47): error SA1003: Operator '(RSACryptoServiceProvider)' should not be followed by whitespace. [/usr/local/google/home/hkj/Projects/firebase-admin-dotnet/public/FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj]
Auth/HttpPublicKeySource.cs(124,30): error SA1003: Operator '(RSAKey)' should not be followed by whitespace. [/usr/local/google/home/hkj/Projects/firebase-admin-dotnet/public/FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj]
```
Fixed by this PR.
=> Fixing a couple of lint errors for .NET 4.5

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseTokenVerifierTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenVerifier.cs
* Adding a 5 minute tolerance to timestamp comparisons
* Updated error messages to include more details
Resolves #28
=>  Tolerating a 5 minute clock skew when verifying JWTs

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseMessagingSnippets.cs, FirebaseAdmin/FirebaseAdmin/Messaging/SendResponse.cs
Samples to appear on https://firebase.google.com/docs/cloud-messaging/send-message
Also made a minor change to some XmlDoc that our tooling could not process/render correctly for the website.
=> Snippets for FCM multicast API

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/IUserInfo.cs, FirebaseAdmin/FirebaseAdmin/Auth/Internal/GetAccountInfoResponse.cs, FirebaseAdmin/FirebaseAdmin/Auth/ProviderUserInfo.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserMetadata.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserRecord.cs
This pull request implements the GetUser() function in FirebaseAuth, closely following the implementation found in the firebase-admin-java project.
=> Implemented FirebaseAuth.GetUser based on the Java implementation

FirebaseAdmin/FirebaseAdmin/Messaging/ApnsConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Aps.cs, FirebaseAdmin/FirebaseAdmin/Messaging/ApsAlert.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushFcmOptions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushNotification.cs
It turns out tools like Doxygen do not correctly render `<see href>` tags in API references. See the intro section of this page for an example: https://firebase.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/aps
This PR changes the API docs to use `<a href>` tags instead. The resulting documentation displays the external links correctly: https://firebase.devsite.corp.google.com/docs/reference/admin/dotnet/class/firebase-admin/messaging/aps
=> Changed <see href> tags to <a tags> in API docs

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
LicenseURL config is being deprecated. LicenseExpression is the new recommended way to specify license details: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
=> Updated license package expression

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
Currently `FirebaseUserManagerTest` only tests the internal `FirebaseUserManager` class. However, in practice this class gets called through the public `FirebaseAuth` API, and that API goes largely untested in the present scheme. This PR updates the test to invoke `FirebaseUserManager` via `FirebaseAuth` for better test coverage.
=> Testing FirebaseUserManager via FirebaseAuth

FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAppTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseExceptionTest.cs, FirebaseAdmin/FirebaseAdmin/AppOptions.cs, FirebaseAdmin/FirebaseAdmin/ErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Extensions.cs, FirebaseAdmin/FirebaseAdmin/FirebaseException.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
This is a first step towards implementing the API changes discussed in #45.
* Implemented the `ErrorCode` enum.
* Adding `ErrorCode` to `FirebaseException`. This property is not currently exposed as public. It will be exposed in a future release.
* Support for handling low-level IO errors (only integrated with FCM at the moment)
go/firebase-error-handling-dotnet
=> Introducing the platform-wide error codes

.gitignore, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FcmOptionsTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidFcmOptions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/ApnsConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/ApnsFcmOptions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FcmOptions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Message.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Util/AnalyticsLabelChecker.cs
Solves https://github.com/firebase/firebase-admin-dotnet/issues/88
=> Added support for analytics_label

FirebaseAdmin/FirebaseAdmin.Tests/HttpErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessagingErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/PlatformErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Util/ErrorHandlingHttpClientTest.cs, FirebaseAdmin/FirebaseAdmin/HttpErrorHandler.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Message.cs, FirebaseAdmin/FirebaseAdmin/Messaging/MessagingErrorHandler.cs, FirebaseAdmin/FirebaseAdmin/PlatformErrorHandler.cs, FirebaseAdmin/FirebaseAdmin/Util/DeserializedResponseInfo.cs, FirebaseAdmin/FirebaseAdmin/Util/ErrorHandlingHttpClient.cs, FirebaseAdmin/FirebaseAdmin/Util/ErrorHandlingHttpClientArgs.cs, FirebaseAdmin/FirebaseAdmin/Util/IDeserializeExceptionHandler.cs, FirebaseAdmin/FirebaseAdmin/Util/IHttpErrorResponseHandler.cs, FirebaseAdmin/FirebaseAdmin/Util/IHttpRequestExceptionHandler.cs, FirebaseAdmin/FirebaseAdmin/Util/IHttpResponseDeserializer.cs, FirebaseAdmin/FirebaseAdmin/Util/ResponseInfo.cs
Following pattern is pretty common in the SDK:
1. Make an HTTP call and read the response to memory.
2. Handle any HTTP error responses.
3. Deserialize the success response.
Each of the above steps can throw exceptions, which we must catch and expose wrapped in the appropriate `FirebaseException` subclass. In this PR I'm implementing a flexible and typesafe framework to implement this pattern.
PR highlights:
1. A new `ErrorHandlingHttpClient<T>` class that will catch various exceptions and rethrow them as instances of `T`.
2. Three new interfaces that can be used to configure the error handling behavior of `ErrorHandlingHttpClient`:
- `IHttpRequestExceptionHandler<T>`
- `IHttpErrorResponseHandler<T>`
- `IDeserializeExceptionHandler<T>`
3. The existing `HttpErrorHandler` has been made to …
=> Implemented ErrorHandlingHttpClient for easy and typesafe error handling

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseMessagingSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/InstanceIdClientTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs, FirebaseAdmin/FirebaseAdmin/Messaging/InstanceIdClient.cs, FirebaseAdmin/FirebaseAdmin/Messaging/InstanceIdServiceResponse.cs
1. Changing the public API to meet the approved design spec (go/dotnet-fcm)
2. Added snippets to appear in https://firebase.google.com/docs/cloud-messaging/manage-topics
=> feat(fcm): Added the SubscribtToTopicAsync() and UnsubscribeFromTopicAsync() APIs

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
Set the `X-GOOG-API-FORMAT-VERSION` header on FCM requests.
Partly related to #45.
=> Requesting detailed error responses from FCM backend

FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
RELEASE NOTE: Fixed an issue that caused async API calls to deadlock in some environments.
Resolves #108
=> fix: Add .ConfigureAwait(false) to all async call

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/IAMSignerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/IAMSigner.cs, FirebaseAdmin/FirebaseAdmin/FirebaseException.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushNotification.cs
* Throwing `FirebaseAuthException` from the custom token creation APIs.
* Throwing `InvalidOperationException` when the service account ID is not set up (this is not an exception that we expect developers to "handle" at runtime, and therefore should not raise a `FirebaseException`)
* Exposed `ErrorCode` from the parent `FirebaseException` class.
This completes the error handling revamp for the .NET Admin SDK.
RELEASE NOTES: `CreateCustomTokenAsync()` API now throws `FirebaseAuthException` if an error occurs while signing custom tokens. If the service account is not correctly configured, this API throws an `InvalidOperationException`.
=> feat(auth): Migrating CreateCustomTokenAsync() APIs to the new error handling scheme

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs, FirebaseAdmin/FirebaseAdmin/Messaging/ApnsFcmOptions.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Notification.cs
* Add image in notification support
* Add unit tests and modified integration test to reflect this change
* In Firebase Cloud Messaging, added 'image' field in the general Notification class, the AndroidNotification class, and the ApnsFcmOptions class.
RELEASE NOTE: Added new APIs for specifying an image URL in notifications.
Resolves #95
=> feat(fcm): Add image in notification support

CONTRIBUTING.md, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/ExportedUserRecordTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/ExportedUserRecord.cs
These values *look* like password hashes, but aren't, leading to
potential confusion.
Additionally, added docs to CONTRIBUTING.md detailing how to add the
permission that causes password hashes to be properly returned as well
as adjusting the test failure message should the developer not add that
permission.
b/141189502
=> Remove (base64) 'REDACTED' passwords from user records.

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorHandler.cs
Added missing EMAIL_EXISTS Auth error message.
Not sure if the DUPLICATE_EMAIL message is already deprecated, as firebase api documentation is not clear about this for me.
RELEASE NOTE: User management APIs now correctly raise `ErrorCode.AlreadyExists` when an already in-use email address is specified for a user.
=> fix(auth): Added EMAIL_EXISTS Auth error message.

.github/scripts/generate_changelog.sh, .github/scripts/publish_package.sh, .github/scripts/publish_preflight_check.sh, .github/workflows/release.yml
Running this portion of the release workflow on Linux, so we can reuse the same shell scripts for preflight and changelog generation.
=> chore: Implementing the publish workflow

FirebaseAdmin/FirebaseAdmin.Tests/Auth/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/EmailActionLinkRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
```
Task<string> GenerateEmailVerificationLinkAsync(string email)
Task<string> GenerateEmailVerificationLinkAsync(string email, ActionCodeSettings settings)
Task<string> GenerateEmailVerificationLinkAsync(string email, ActionCodeSettings settings, CancellationToken cancellationToken)
```
=> feat(auth): Added APIs for generating email verification links

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserRecordArgs.cs
Ability to revoke previously issued refresh tokens by setting the `validSince` property on user accounts.
Resolves #150
=> feat(auth): Added RevokeRefreshTokensAsync() API

CONTRIBUTING.md
Addresses #183, which requires additional setup instructions for allowing authentication integration tests to pass. 
Resolves #183
=> chore: Add instructions to CONTRIBUTING.md for manually enabling Email/Password authentication

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Hash/UserImportHashTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/ImportUserRecordArgsTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/UserImportOptionsTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/UserProviderTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Hash/Sha1.cs, FirebaseAdmin/FirebaseAdmin/Auth/Hash/Sha256.cs, FirebaseAdmin/FirebaseAdmin/Auth/ImportUserRecordArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserMetadata.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserProvider.cs
This is a separate pull request because the other PR was getting too big (note that it will merge back into the other `bulk-user-import` branch).
Addressed feedback from the last round of review. Another note is that I brought up the Base64Url encoding prior, I think the implementation is ok as it is similar to the Java behavior and it is verified by the `SignerKey` being properly URL encoded in the tests here.
One remark is the addition of `NullValueHandling = NullValueHandling.Ignore` for all properties (except Uid) when being serialized for `ImportUserRecordArgs`. 
Newtonsoft has the ability to choose to ignore null values when the serialize function is invoked, but in this case `PostAndDeserializeAsync` handles the serialization using …
=> Address feedback for user import unit tests

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/AuthProviderConfigs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ListOidcProviderConfigsRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ListProviderConfigsOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ListProviderConfigsPageManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ListProviderConfigsRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigManager.cs
Added the method for listing OIDC provider configs:
```
PagedAsyncEnumerable<AuthProviderConfigs<OidcProviderConfig>, OidcProviderConfig> 
ListOidcProviderConfigsAsync(ListProviderConfigsOptions options)
```
Elements of the implementation mostly copied from the existing `ListUsersAsync()` API. Uses REST API utils provided by `Google.Api.Gax` to handle paging.
=> feat(auth): Added ListOidcProviderConfigsAsync() API

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/ProviderConfigTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/AuthProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfig.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigClient.cs
Implemented `UpdateProviderConfigAsync()` support for `SamlProviderConfigArgs`. There's some room for code de-duplication here, but I'd rather do that refactor in a separate PR.
=> feat(auth): Added support for updating SAML provider configs

FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigClient.cs
Lot of the RPC handling logic is duplicated across `OidcProviderConfigClient` and `SamlProviderConfigClient`. This refactor moves all the common code into the parent class, and let the child classes customize only the necessary bits.
=> fix: Moving common rpc logic to ProviderConfigClient

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/ProviderConfigTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigClient.cs
Added `ListSamlProviderConfigAsync()` API to `FirebaseAuth`. Fixed a couple of issues with existing tests.
=> feat(auth): Added ListSamlProviderConfigs API

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigManager.cs
Implemented API for deleting auth provider configurations. This completes the IdP configuration management implementation. Integration tests will be added in a future PR.
=> feat(auth): Added DeleteProviderConfigAsync() API

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/TestRankAttribute.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/TestRankOrderer.cs
Using XUnit fixtures to reuse the same `AuthProviderConfig` across multiple test cases. Introduced a way to order the test cases within a class by applying a custom attribute.
Staging build triggered for verification.
=> chore: Added integration tests for SAML/OIDC IdP management

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorHandler.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/Tenant.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantManager.cs
* Added `TenantManager` class.
* Added `Tenant` class
* Added `TenantManager.GetTenantAsync()` API
* Exposed `FirebaseAuth.TenantManager` property
go/firebase-mt-dotnet
=> feat(auth): Added TenantManager, Tenant and GetTenantAsync APIs

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/ErrorInfo.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/ImportUserRecordArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserImportHash.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserImportOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserImportRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserImportResult.cs
I was trying to improve the test coverage of this API, and in the processes uncovered several bugs and documentation errors. Specifically the current implementation does not correctly handle user import error responses due to issues in response unmarshaling (missing setters and constructors). I've addressed these issues here.
RELEASE NOTE: Fixed a bug in the `ImportUsersAsync()` that was preventing the correct handling of user import errors.
=> fix(auth): Fixing the error response parsing of ImportUsersAsync()

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/FirebaseTokenVerifierTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/IdTokenVerificationTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseToken.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifierArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs
* Implemented support for verifying tenant-scoped ID tokens, and exposed `TenantId` from the `FirebaseToken` class.
* Moved `VerifyIdTokeAsync()` APIs to the `AbstractFirebaseAuth` class.
* Updated unit tests.
* Set the `LangVersion` to latest in the `FirebaseAdmin.Tests.csproj` file (we already use the same setting in `FirebaseAdmin.csproj`). This enables us to use latest language features like `private protected` which are useful in implementing better encapsulated test utils.
=> feat(auth): Adding tenant-aware token verification support

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/IdTokenVerificationTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/JwtTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/MockTokenBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/SessionCookieVerificationTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/TestOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifierArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs
* Moved `VerifySessionCookieAsync()` APIs to `AbstractFirebaseAuth`.
* Added support for initializing test session cookie verifiers via `AuthBuilder` and `TestOptions`.
=> feat(auth): Support for verifying tenant-scoped session cookies

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/SessionCookieOptions.cs
* Moved `CreateSessionCookieAsync()` APIs to `AbstractFirebaseAuth`.
* Overrode `CreateSessionCookieAsync()` in `TenantAwareFirebaseAuth` to perform an ID token verification locally before creating the session cookie. This ensures the tenant ID of the input ID token matches the client.
=> feat(auth): Support for creating tenant-scoped session cookies

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/ProviderTestConfig.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/TestOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ApiClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigManager.cs, FirebaseAdmin/FirebaseAdmin/Util/HttpUtils.cs
* Moved all provider config management APIs to `AbstractFirebaseAuth`.
* Implemented support for tenant-aware provider config management in `ProviderConfigManager` and `ApiClient`.
* Turned `ProviderConfigTestUtils` into `ProviderTestConfig`, so it can be used as the means to parametrize unit tests.
=> feat(auth): Tenant-aware provider config management

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractFirebaseAuthTest.cs
This creates a few extra user accounts during testing, but gives much better granularity in test failure reporting.
=> chore: Split long user lifecycle test into multiple test cases

FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ApiClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/ListUsersRequest.cs, FirebaseAdmin/FirebaseAdmin/Util/AdaptedListResourcesRequest.cs, FirebaseAdmin/FirebaseAdmin/Util/ListResourcesRequest.cs
* Extending `ListResourcesRequest` for `ListUsers()` and `ListProviderConfigsAsync()` methods.
* Decoupled `ListResourcesRequest` from `ErrorHandlingHttpClient` by introducing a new `AdaptedListResourcesRequest` class.
=> fix(auth): Reusing ListResourcesRequest util in all pagination APIs

FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/HttpPublicKeySource.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/PublicKey.cs, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj, README.md
* Added `net461` to the list of target frameworks.
* Added a note indicating that the support `net45` and `netstandard1.5` are on the way out.
Laying the groundwork for #251 
RELEASE NOTE: change: Support for `net45` and `netstandard1.5` frameworks has been deprecated. Developers are advised to use `net461` or `netstandard2.0`.
=> chore: Deprecating support for net45 and netstandard1.5

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseMessagingSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MulticastMessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs, FirebaseAdmin/FirebaseAdmin/Messaging/MulticastMessage.cs
RELEASE NOTE: `MulticastMessage` and `SendAllAsync()` APIs now support sending up to 500 messages in a batch.
=> feat(fcm): Support for sending up to 500 messages in a batch

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
RELEASE NOTE: Setting the `ApplicationName` property for the batch request client, which resolves a warning log message seen in previous versions of the SDK.
Resolves #259
=> fix(fcm): Setting ApplicationName property for the batch client

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractOidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractSamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAdmin.IntegrationTests.csproj, FirebaseAdmin/FirebaseAdmin.IntegrationTests/IntegrationTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAdmin.Snippets.csproj, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAppSnippets.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/TopicManagementResponseTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/IUserInfo.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/HttpPublicKeySource.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/PublicKey.cs, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj, FirebaseAdmin/FirebaseAdmin/FirebaseApp.cs, FirebaseAdmin/FirebaseAdmin/Messaging/ApnsConfig.cs, FirebaseAdmin/FirebaseAdmin/Messaging/BatchResponse.cs, FirebaseAdmin/FirebaseAdmin/Messaging/CriticalSound.cs, FirebaseAdmin/FirebaseAdmin/Messaging/MulticastMessage.cs, FirebaseAdmin/FirebaseAdmin/Messaging/WebpushConfig.cs, README.md
- Project target frameworks replaced with .NET Framework 4.6.1 and .NET Standard 2.0 to be consistent with the frameworks supported by other .NET libraries associated with Google Cloud Platform.
- Removed Google.Api.Gax
- Updated Google.Api.Gax.Rest to 3.2.0
- Updated Google.Apis.Auth to 1.49.0
- Updated System.Collections.Immutable to 1.7.1
- Fixed tests
API CHANGE: Dropped support for `netstandard1.5` and `net45` target frameworks. Developers are now required to use `netstandard2.0` or `net461`.
API CHANGE: Upgraded the dependency `Google.Api.Gax` to the latest major version. Developers that use the [`PagedAsyncEnumerable`](https://googleapis.github.io/google-cloud-dotnet/docs/api/Google.Api.Gax.PagedAsyncEnumerable-2.html) interface from this package (usually as the return value of …
=> change: Update project target frameworks and dependencies

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthEmulatorTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/IdTokenVerificationTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/JwtTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenVerifierArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Utils.cs
Added emulator support for `VerifyIdTokenAsync()` method. In the emulator mode:
* Algorithm and KID header validations are skipped
* Signature verification is skipped
=> feat(auth): Supporting VerifyIdToken() API with emulator

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthEmulatorTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/CustomTokenTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/CustomTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/FirebaseTokenFactoryTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/IdTokenVerificationTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/JwtTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/MockTokenBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/TestOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/EmulatorSigner.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenFactory.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/IAMSigner.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/ISigner.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/JwtUtils.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/ServiceAccountSigner.cs
Implemented support for creating custom tokens for the emulator. In the emulator mode:
* The `alg` header is set to `none`.
* Signature is set to empty byte sequence.
Bulk of the changes are just refactoring the existing tests. I've updated `CustomTokenTest` to be more inline with other test classes like `IdTokenVerificationTest`, where we test behavior via parameterization, as opposed to creating `FirebaseApp` instances with different configurations.
=> feat(auth): Emulator support for CreateCustomTokenAsync() API

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthEmulatorTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantManager.cs
Ability to send `TenantManager` RPCs to the emulator. This is done by:
* updating the `baseUrl` property in the `TenantManager`, and
* using emulator credentials to authorize emulator requests.
=> feat(auth): Adding emulator support to TenantManager API

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorHandler.cs
Catch EMAIL_NOT_FOUND when /accounts:sendOobCode is called for password reset on a user that does not exist.
=> fix(auth): adds missing EMAIL_NOT_FOUND error code

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractOidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/OidcProviderConfigFixture.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfig.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfigArgs.cs
Provides an option for developers to specify the OAuth response type for their OIDC provider (either one of these can be set:):
- id_token
- code (if set, must also set the client secret)
=> feat(auth): enables OIDC auth code flow

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs, FirebaseAdmin/FirebaseAdmin/Messaging/LightSettings.cs, FirebaseAdmin/FirebaseAdmin/Messaging/LightSettingsColor.cs, FirebaseAdmin/FirebaseAdmin/Messaging/Util/TimeConverter.cs
I couldn't get xUnit to compare `LightSettingsColor` so I assert the properties separately.
Let me know if there's changes I should make.
Thanks!
Related to: #153
=> Closes #153. Add additional FCM options for Android Notification

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
- Github Actions images no longer support .net framework 4.6, breaking CI tests and the release process.
- Updated workflow files to build Nuget package [targeting the .net framework](https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies) on ubuntu-latest.
=> chore: Build .net framework targets on linux

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/MockMessageHandler.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
`SendEachAsync` vs `SendAllAsync`
1. `SendEachAsync` sends one HTTP request to V1 Send endpoint for each message in the list. `SendAllAsync` sends only one HTTP request to V1 Batch Send endpoint to send all messages in the list.
2. `SendEachAsync` calls `Task.WhenAll` to wait for all `httpClient.SendAndDeserializeAsync` calls to complete and construct a `BatchResponse` with all `SendResponse`s. An `httpClient.SendAndDeserializeAsync` call to V1 Send endpoint either completes with a success or throws an exception. So if an exception is thrown out, the exception will be caught in `SendEachAsync` and turned into a `SendResponse` with an exception. Therefore, unlike `SendAllAsync`, `SendEachAsync` does not always throw an exception for a total failure. It can also return a `BatchResponse` …
=> feat(fcm): Implement `SendEachAsync` and `SendEachForMulticastAsync`

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingClientTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/MockMessageHandler.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessagingClient.cs
* Deprecate `SendAllAsync`() and `SendMulticastAsync` APIs.
* Add `SendEachAsync` and `SendEachForMulticastAsync` APIs
`SendEachAsync` vs `SendAllAsync`
1. `SendEachAsync` sends one HTTP request to V1 Send endpoint for each message in the list. `SendAllAsync` sends only one HTTP request to V1 Batch Send endpoint to send all messages in the list.
2. `SendEachAsync` calls `Task.WhenAll` to wait for all `httpClient.SendAndDeserializeAsync` calls to complete and construct a `BatchResponse` with all `SendResponse`s. An `httpClient.SendAndDeserializeAsync` call to V1 Send endpoint either completes with a success or throws an exception. So if an exception is thrown out, the exception will be caught in `SendEachAsync` and turned into a `SendResponse` with an exception. Therefore, unlike …
=> feat(fcm): Add `SendEachAsync` and `SendEachForMulticastAsync`  for FCM batch send

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAppSnippets.cs
In the internal bug b/290344815 we had been discussing how to initialize SDK and we come up with working version which is different than documentation on the page: https://firebase.google.com/docs/admin/setup?hl=pl#initialize_the_sdk_in_non-google_environments.
This is only part of the change. The second part is done in cider.  cl/555243967
=> New snippet with project id defined.

.github/scripts/builder.sh, .github/scripts/run_integration_tests.sh, .github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAdmin.IntegrationTests.csproj, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAdmin.Snippets.csproj, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/CustomTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/JwtTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/ServiceAccountSignerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAppTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/BatchResponseTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
- Dropped `net461` support
- Added `net462` and `net6.0`+ support
=> chore: Bump supported .NET versions to `net462` and `net6.0`+

README.md
Support for .NET Framework 4.6.1 is now deprecated.
Next major version of the Admin SDK will terminate support for this
framework. Developers are advised to upgrade their runtime frameworks
accordingly.
=> (chore): Marked net 4.6.1 as deprecated

.github/dependabot.yml
Should now point to `FirebaseAdmin/FirebaseAdmin.sln` which has references to each of the nested `*.csproj` file.
=> chore: fix dependabot .NET path

.github/workflows/nightly.yml, .github/workflows/release.yml
Starting November 30, 2024, GitHub Actions customers will no longer be able to use v1 to v3 of actions/upload-artifact or actions/download-artifact.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> (chore): Bump `upload-artifact` and `download-artifact` to v4

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Dropped support for .NET Framework 4.6.1. Developers are now required to use .NET Framework 4.6.2+ or .NET 6.0+
=> [chore] Release 3.0.0

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Dropped support for .NET Framework 4.6.1. Developers are now required to use .NET Framework 4.6.2+ or .NET 6.0+
=> [chore] Release 3.0.0 Take 2

FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs
Fixes: #381, and #370 
Thanks @martinwiboe for the contribution in #329
=> fix(fcm): Use Invariant Culture when generating event_time

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidConfig.cs
Added the `DirectBootOk` field to the `AndroidConfig` type.
=> feat(fcm): Add `DirectBootOk` field to `AndroidConfig`

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
Ubuntu 24.04 requires mono to be installed in order to run tests in net462.
=> chore: Add mono install step to GHAs

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/MessageTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/AndroidNotification.cs, FirebaseAdmin/FirebaseAdmin/Messaging/NotificationProxy.cs
* Adds `proxy` field to `AndroidNotification`
=> feat(fcm): Support `proxy` field in FCM `AndroidNotification`

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/GetUsersTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAdmin.IntegrationTests.csproj, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAdmin.Snippets.csproj, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj, README.md
Updates:
* `xunit` 2.7.0 to 2.9.3
* `System.Linq.Async` 2.7.0 to 2.9.3
Also fixes README.md status badge
=> chore: Update test dependencies

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AbstractFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthErrorHandlerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorHandler.cs
The auth error code parser incorrectly mapped known error codes to unknown errors due to additional whitespace from the expected auth error message. This whitespace is now trimmed and correctly mapped to the corresponding auth error code.
=> fix(auth): Fixed auth error code parsing
