firebase/firebase-admin-dotnet

.travis.yml
https://travis-ci.org/firebase/firebase-admin-dotnet
Support based on https://docs.travis-ci.com/user/languages/csharp/
=> Basic Travis CI Integration

package_release.sh, prepare_release.sh
Prepare step: Verifies and updates the version number, runs all tests
Package step: Builds the release artifact (nupkg file)
=> Adding scripts to prepare and build releases

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseMessagingSnippets.cs
Samples to appear on https://firebase.google.com/docs/cloud-messaging/admin/send-messages
=> Sample snippets for the FCM API

FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAppTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingTest.cs, FirebaseAdmin/FirebaseAdmin/AppOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenFactory.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/FirebaseApp.cs, FirebaseAdmin/FirebaseAdmin/Messaging/FirebaseMessaging.cs
Added support for configuring HttpClientFactory.  Needed for Proxy support.  Also provide further configuration capabilities now that HttpClientFactory is exposed.
=> Proxy Support

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAppTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Messaging/FirebaseMessagingTest.cs
Build error caused due to another PR that got merged while #34 was under review.
Also updated the CHANGELOG.
=> Fixing a build error in tests

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/UserRecordTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserMetadata.cs
As decided in go/dotnet-user-mgt
Also added a few snippets to appear on https://firebase.google.com/docs/auth/admin/manage-users
=> Use nullable types for UserMetadata fields

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserRecordArgs.cs
=> Implemented the UpdateUserAsync() API

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/ExportedUserRecordTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/DownloadAccountResponse.cs, FirebaseAdmin/FirebaseAdmin/Auth/ExportedUserRecord.cs, FirebaseAdmin/FirebaseAdmin/Auth/ExportedUserRecords.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/ListUsersOptions.cs, FirebaseAdmin/FirebaseAdmin/Auth/ListUsersPageManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/ListUsersRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserRecord.cs
* Cleaned up the public API according to go/dotnet-user-mgt
* Added tests to cover different ways of iterating through user accounts
Follow up to #58
=> Updating the ListUsers() Implementation

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Similar to https://github.com/googleapis/google-api-dotnet-client/blob/master/Src/Support/Google.Apis.Core/Google.Apis.Core.csproj
=> Adding .NET standard 2.0 to supported frameworks

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
Snippets to appear in https://firebase.google.com/docs/auth/admin/manage-users
=> Added snippets for new user management APIs

CONTRIBUTING.md, FirebaseAdmin/FirebaseAdmin.Tests/FirebaseAdmin.Tests.csproj
Code coverage support with coverlet: https://github.com/tonerdo/coverlet
```
$ dotnet test FirebaseAdmin.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
Build started, please wait...
Build completed.
Test run for /Users/hkj/Projects/firebase-admin-dotnet/public/FirebaseAdmin/FirebaseAdmin.Tests/bin/Debug/netcoreapp2.0/FirebaseAdmin.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Total tests: 235. Passed: 235. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.8815 Seconds
Calculating coverage result...
Generating report '/Users/hkj/Projects/firebase-admin-dotnet/public/FirebaseAdmin/FirebaseAdmin.Tests/coverage. …
```
=> Coverlet code coverage utility integration

CHANGELOG.md, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
=> Bumped version to 1.9.0

FirebaseAdmin/FirebaseAdmin/Auth/IAMSigner.cs
Added missing Credential args to `ErrorHandlingHttpClient`
=> Added missing Credential args to ErrorHandlingHttpClient

FirebaseAdmin/FirebaseAdmin.Tests/Auth/IAMSignerTest.cs
=> Updated IAMSignerTest

FirebaseAdmin/FirebaseAdmin.Tests/Messaging/InstanceIdClientTest.cs, FirebaseAdmin/FirebaseAdmin/Messaging/InstanceIdClient.cs
Current implementation handles IID (topic management) errors via `MessagingErrorHandler` essentially assuming they are same as other FCM errors. But IID API does not follow the OnePlatform error format.
This PR corrects for this discrepancy.
=> fix(fcm): Fixed error handling in the topic management APIs

FirebaseAdmin/FirebaseAdmin.Tests/Auth/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/EmailActionLinkRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
Added `GenerateSignInWithEmailLinkAsync()` methods.
=> feat(auth): Added APIs for generating email sign-in links

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
RC staged to trigger the new integration tests.
=> fix(auth): Integration tests and sample snippets for email action links

.github/workflows/release.yml, FirebaseAdmin/FirebaseAdmin.Tests/Auth/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorHandler.cs
Also corrected a config error in the release publish workflow config.
=> feat(auth): Added InvalidDynamicLinkDomain Error Code

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
Also added snippets for https://firebase.google.com/docs/auth/admin/manage-sessions
=> fix(auth): Integration test for RevokeRefreshTokensAsync()

FirebaseAdmin/FirebaseAdmin.Tests/Auth/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseTokenVerifierTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/SessionCookieVerificationTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AuthErrorCode.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenVerifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseTokenVerifierArgs.cs
```
Task<FirebaseToken> VerifySessionCookieAsync(string cookie)
Task<FirebaseToken> VerifySessionCookieAsync(string cookie, boolean checkRevoked)
```
RELEASE NOTE: Added `VerifySessionCookieAsync()` method for verifying Firebase session cookies in backend applications.
=> feat(auth): Added VerifySessionCookieAsync() APIs

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAdmin.Snippets.csproj, FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
Snippets use the ASP MVC framework.
To appear on https://firebase.google.com/docs/auth/admin/manage-cookies
=> chore(auth): Added integration tests and snippets for session management

.github/workflows/release.yml, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Also fixed a typo in release script.
=> [chore] Release 1.12.0

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseExceptionSnippets.cs, FirebaseAdmin/FirebaseAdmin.Tests/Util/ErrorHandlingHttpClientTest.cs
Added snippets that would appear in the proposed error handling guide.
=> chore: Added snippets for error handling

FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs
=> Remove {@code foo} tag.

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
Based on:
https://github.com/firebase/snippets-node/pull/86
=> Add auth bulk get/delete snippets

FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAuthTest.cs
- Fixes the hashing algorithm parameters so that they are valid (i.e., matching key/salt that resolves to password)
- Verifies that the user was imported correctly by signing in and asserting that the id token returned is not null or empty
=> Enhance user import integration test by verifying user can login 

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/AuthProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/OidcProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigManager.cs
Added support for updating an `OidcProviderConfig`.
=> feat(auth): Added UpdateProviderConfigAsync() API

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/OidcProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/ProviderConfigTestUtils.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Providers/SamlProviderConfigTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/SamlProviderConfigClient.cs
* Added `SamlProviderConfigArgs` class.
* Added support for creating new SAML auth provider configs.
=> feat(auth): Added SamlproviderConfigArgs API

FirebaseAdmin/FirebaseAdmin.Snippets/FirebaseAuthSnippets.cs
Sample snippets to appear on https://cloud.google.com/identity-platform/docs/managing-providers-programmatically
=> chore: Added sample snippets for IdP config APIs

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/FirebaseAuthTest.cs
Continuing from #219.
Moved `FirebaseAuthTest` to the new `IntegrationTest.Auth` namesapce. Updated the test to use `TemporaryUserBuilder`.
=> chore: Moved FirebaseAuthTest to the Auth namespace

FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseToken.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/Tenant.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantArgs.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Providers/ProviderConfigClient.cs, FirebaseAdmin/FirebaseAdmin/Util/HttpUtils.cs
* Converted the `Tenant.Args` class to the public `TenantArgs` class.
* Implemented create and update methods for tenants.
* Moved some of the shared http logic to a new `HttpUtils` class.
=> feat(auth): Added CreateTenantAsync() and UpdateTenantAsync() APIs

FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantManager.cs
* Added `AbstractFirebaseAuth` class and extended it in `FirebaseAuth` and `TenantAwareFirebaseAuth`.
* Implemented `TenantManager.AuthForTenant()` method.
=> feat(auth): Added TenantAwareFirebaseAuth class

FirebaseAdmin/FirebaseAdmin.Tests/Auth/AuthBuilder.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/ExportedUserRecordTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Jwt/CustomTokenTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/UserRecordTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/EmailActionRequestTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Users/FirebaseUserManagerTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/AbstractFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/DeleteUsersResult.cs, FirebaseAdmin/FirebaseAdmin/Auth/EmailIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/ExportedUserRecord.cs, FirebaseAdmin/FirebaseAdmin/Auth/FirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/GetUsersResult.cs, FirebaseAdmin/FirebaseAdmin/Auth/Multitenancy/TenantAwareFirebaseAuth.cs, FirebaseAdmin/FirebaseAdmin/Auth/PhoneIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/ProviderIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/ProviderUserInfo.cs, FirebaseAdmin/FirebaseAdmin/Auth/UidIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserImportResult.cs, FirebaseAdmin/FirebaseAdmin/Auth/UserRecord.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/BatchDeleteResponse.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/DownloadAccountResponse.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/EmailActionLinkRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/FirebaseUserManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/GetAccountInfoRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/GetAccountInfoResponse.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/ListUsersPageManager.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/ListUsersRequest.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/UserImportRequest.cs
Created a new child namespace to house the remaining `internal` classes in the top-level `Auth` namespace.
=> chore: Added FirebaseAdmin.Auth.Users namespace

FirebaseAdmin/FirebaseAdmin.Tests/Auth/DeleteUsersResultTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/Multitenancy/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.Tests/Auth/UserIdentifierTest.cs, FirebaseAdmin/FirebaseAdmin/Auth/DeleteUsersResult.cs, FirebaseAdmin/FirebaseAdmin/Auth/Jwt/FirebaseTokenFactory.cs, FirebaseAdmin/FirebaseAdmin/Auth/ProviderIdentifier.cs, FirebaseAdmin/FirebaseAdmin/Auth/Users/FirebaseUserManager.cs
Adding some unit tests to increase the overall coverage in Auth.
=> chore: More unit tests

FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/AuthIntegrationUtils.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/FirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TemporaryUserBuilder.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TenantAwareFirebaseAuthTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TenantFixture.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/Auth/TenantManagerTest.cs, FirebaseAdmin/FirebaseAdmin.IntegrationTests/FirebaseAdmin.IntegrationTests.csproj
* Added `TenantManagerTest` to verify the life cycle operations of a tenant.
* Added `TenantAwareFirebaseAuthTest` to verify tenant-scoped auth operations.
* Integration tests triggered in CI
=> chore: Adding integration tests for multi-tenancy support

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
=> [chore] Release 1.16.0

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Reverts firebase/firebase-admin-dotnet#248
=> Revert "[chore] Release 1.16.0"

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
This time with the publish label.
=> [chore] Release 1.16.0 take 2

FirebaseAdmin/FirebaseAdmin/Auth/Jwt/IAMSigner.cs
Point SignBlob to iamcredentials instead of iam
=> fix(auth): Migrate IAM SignBlob to IAMCredentials SignBlob

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
=> [chore] Release 2.0.0

.github/ISSUE_TEMPLATE/bug_report.md
- Remove delayed response message for holidays
=> Remove delayed response message for holidays

.github/workflows/nightly.yml
=> chore: Add nightly build workflow

.github/ISSUE_TEMPLATE/bug_report.md
Adding delayed response message for holidays
=> Add delayed response message for holidays

.github/ISSUE_TEMPLATE/bug_report.md
Reverts firebase/firebase-admin-dotnet#311
=> Revert "Add delayed response message for holidays"

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Reverts firebase/firebase-admin-dotnet#319
=> Revert "[chore] Release 2.3.0"

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Includes https://github.com/firebase/firebase-admin-dotnet/pull/317 and https://github.com/firebase/firebase-admin-dotnet/pull/203
=> [chore] Release 2.3.0 Take 2

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
=> [chore] Release 2.4.0

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Reverts firebase/firebase-admin-dotnet#350
=> Revert "[chore] Release 2.4.0"

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
This reverts commit f49864cfe5891b0a35d0ae92c11835b8b29e634d.
=> Revert "[chore] Release 2.4.1 (#386)"

CONTRIBUTING.md, FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj, README.md
=> Add `README.md` to Nuget and update `CONTRIBUTING.md`

.github/workflows/nightly.yml, .github/workflows/release.yml
Reverts firebase/firebase-admin-dotnet#395
=> Revert "(chore): Bump `upload-artifact` and `download-artifact` to v4"

FirebaseAdmin/FirebaseAdmin/FirebaseAdmin.csproj
Reverts firebase/firebase-admin-dotnet#397
=> Revert "[chore] Release 3.0.0"
